# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Users\Alex\Documents\IRL\Programmes\Premier_projet_python\fenetre.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 339)
        self.pB_ajouter = QtWidgets.QPushButton(Form)
        self.pB_ajouter.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.pB_ajouter.setObjectName("pB_ajouter")
        self.pB_supprimer = QtWidgets.QPushButton(Form)
        self.pB_supprimer.setEnabled(True)
        self.pB_supprimer.setGeometry(QtCore.QRect(210, 300, 75, 23))
        self.pB_supprimer.setObjectName("pB_supprimer")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label.setObjectName("label")
        self.lE_adresse = QtWidgets.QLineEdit(Form)
        self.lE_adresse.setGeometry(QtCore.QRect(90, 40, 201, 20))
        self.lE_adresse.setCursorPosition(0)
        self.lE_adresse.setObjectName("lE_adresse")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lE_appareil = QtWidgets.QLineEdit(Form)
        self.lE_appareil.setGeometry(QtCore.QRect(90, 70, 201, 20))
        self.lE_appareil.setObjectName("lE_appareil")
        self.cbB_proprietaire = QtWidgets.QComboBox(Form)
        self.cbB_proprietaire.setGeometry(QtCore.QRect(90, 10, 201, 22))
        self.cbB_proprietaire.setObjectName("cbB_proprietaire")
        self.pB_activer_ajouter = QtWidgets.QPushButton(Form)
        self.pB_activer_ajouter.setGeometry(QtCore.QRect(300, 10, 21, 21))
        self.pB_activer_ajouter.setObjectName("pB_activer_ajouter")
        self.pB_supprimer_annuler = QtWidgets.QPushButton(Form)
        self.pB_supprimer_annuler.setGeometry(QtCore.QRect(330, 10, 21, 21))
        self.pB_supprimer_annuler.setObjectName("pB_supprimer_annuler")
        self.lE_proprietaire = QtWidgets.QLineEdit(Form)
        self.lE_proprietaire.setGeometry(QtCore.QRect(90, 10, 201, 20))
        self.lE_proprietaire.setObjectName("lE_proprietaire")
        self.tW_bd = QtWidgets.QTableWidget(Form)
        self.tW_bd.setGeometry(QtCore.QRect(10, 100, 360, 191))
        self.tW_bd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_bd.setAutoScroll(True)
        self.tW_bd.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tW_bd.setShowGrid(True)
        self.tW_bd.setCornerButtonEnabled(True)
        self.tW_bd.setRowCount(0)
        self.tW_bd.setColumnCount(3)
        self.tW_bd.setObjectName("tW_bd")
        item = QtWidgets.QTableWidgetItem()
        self.tW_bd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_bd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_bd.setHorizontalHeaderItem(2, item)
        self.tW_bd.horizontalHeader().setCascadingSectionResizes(False)
        self.tW_bd.horizontalHeader().setDefaultSectionSize(120)
        self.tW_bd.verticalHeader().setVisible(False)
        self.tW_bd.verticalHeader().setStretchLastSection(False)
        self.lE_proprietaire.raise_()
        self.pB_ajouter.raise_()
        self.pB_supprimer.raise_()
        self.label.raise_()
        self.lE_adresse.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lE_appareil.raise_()
        self.cbB_proprietaire.raise_()
        self.pB_activer_ajouter.raise_()
        self.pB_supprimer_annuler.raise_()
        self.tW_bd.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pB_ajouter.setText(_translate("Form", "Ajouter"))
        self.pB_supprimer.setText(_translate("Form", "Supprimer"))
        self.label.setText(_translate("Form", "Adresse MAC"))
        self.lE_adresse.setInputMask(_translate("Form", "NN:NN:NN:NN:NN:NN"))
        self.lE_adresse.setText(_translate("Form", ":::::"))
        self.label_2.setText(_translate("Form", "Propriétaire"))
        self.label_3.setText(_translate("Form", "Appareil"))
        self.pB_activer_ajouter.setText(_translate("Form", "+"))
        self.pB_supprimer_annuler.setText(_translate("Form", "-"))
        item = self.tW_bd.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Appareil"))
        item = self.tW_bd.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Adresse"))
        item = self.tW_bd.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Propriétaire"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

